import sqlalchemy as sa
from alembic import op

import app.db

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("cash", app.db.Money(precision=24, scale=8), nullable=True),
        sa.Column("as_of", app.db.AwareTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("market", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("share_class", sa.String(), nullable=False),
        sa.Column("qdii", sa.Boolean(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("benchmark_symbol", sa.String(), nullable=True),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("updated_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("created_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.Column("invested_value", app.db.Money(precision=24, scale=8), nullable=False),
        sa.Column("cash_value", app.db.Money(precision=24, scale=8), nullable=True),
        sa.Column("total_value", app.db.Money(precision=24, scale=8), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("instrument_id", sa.String(), nullable=False),
        sa.Column("quantity", app.db.Money(precision=24, scale=8), nullable=True),
        sa.Column("market_value", app.db.Money(precision=24, scale=8), nullable=False),
        sa.Column("holding_profit", app.db.Money(precision=24, scale=8), nullable=True),
        sa.Column("average_cost", app.db.Money(precision=24, scale=8), nullable=True),
        sa.Column("as_of", app.db.AwareTime(timezone=True), nullable=True),
        sa.Column("acquired_on", sa.Date(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "instrument_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("positions")
    op.drop_table("portfolio_snapshots")
    op.drop_table("instruments")
    op.drop_table("accounts")
    # ### end Alembic commands ###
