import sqlalchemy as sa
from alembic import op

import app.db

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_observations",
        sa.Column("series", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", app.db.Money(precision=24, scale=8), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("retrieved_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("series", "date"),
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("published_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "provider_cache",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "price_history",
        sa.Column("instrument_id", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("nav", app.db.Money(precision=24, scale=8), nullable=False),
        sa.Column("total_return", app.db.Money(precision=24, scale=8), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("retrieved_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("instrument_id", "date"),
    )
    op.create_table(
        "daily_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_key", sa.String(), nullable=False),
        sa.Column("started_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.Column("finished_at", app.db.AwareTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("snapshot_id", sa.String(), nullable=True),
        sa.Column("pipeline_version", sa.String(), nullable=False),
        sa.Column("health", sa.JSON(), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("telemetry", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("report", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["portfolio_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_key"),
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("daily_run_id", sa.String(), nullable=False),
        sa.Column("instrument_id", sa.String(), nullable=False),
        sa.Column("created_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("recommendation_type", sa.String(), nullable=False),
        sa.Column("proposed_amount", app.db.Money(precision=24, scale=8), nullable=False),
        sa.Column("current_price", app.db.Money(precision=24, scale=8), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["daily_run_id"],
            ["daily_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendations")
    op.drop_table("daily_runs")
    op.drop_table("price_history")
    op.drop_table("provider_cache")
    op.drop_table("news_items")
    op.drop_table("macro_observations")
    # ### end Alembic commands ###
