import sqlalchemy as sa
from alembic import op

import app.db

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_outcomes",
        sa.Column("recommendation_id", sa.String(), nullable=False),
        sa.Column("updated_at", app.db.AwareTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("recommendation_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendation_outcomes")
    # ### end Alembic commands ###
